#+TITLE: /Annotated checklist of things by or about/\\
James P. Ascher
#+AUTHOR: James P. Ascher
#+EMAIL: james.ascher@gmail.com
#+DATE: Jan. 14, 2016


Like any bibliographical project, this is necessarily selective based
on the material available—in this case—on the web. If you want a CV,
it’s below.

* Biographies
** [[http://scholarslab.org/people/james-p-ascher/]["James P. Ascher · Scholars' Lab,"]] Scholars' Lab, University of Virginia, last modified 2015.
   Praxis Fellow for 2015-16, studying representations of time within
   digital humanities with a particular focus on literate programming,
   language, and the forms of documents.
** [[http://gradstudies.dev.uvaits.virginia.edu/node/315]["Presidential Fellows in Data Science, 2015-2016 | gradstudies.virginia.edu,"]] Office of Graduate & Postdoctoral Affairs, University of Virginia, last modified 2015.
   Media studies and bibliographical type approaches to the the way
   people make arguments using data; collaborative and
   interdisciplinary.
** [[http://www.engl.virginia.edu/people/jpa4q]["Department of English,"]] University of Virginia, last modified 2013.
   Studying English at the University of Virginia, bibliography,
   digital humanities, 18th century, British, and American.
** [[https://virginia.academia.edu/JamesPAscher]["James P. Ascher | University of Virginia - Academia.edu,"]] last modified 2015.
   Traditional academic CV and select publications, mostly related to
   rare book librarianship, and his work as Assistant Professor of
   Libraries and English at CU Boulder.

* Bibliography/Media Studies
** Ascher, James P. "The Wordes Moote be Cosyn to the Dede: Diplomatic Transcription and Shifting Senses of Exactness Toward the Ecosystem of Digital Reproduction," /Appositions: Studies in Renaissance / Early Modern Literature & Culture/ 8 (2011) [[http://appositions.blogspot.com/2011/05/james-p-ascher-diplomatic-e.html]]
   Some ways in which the expectations for an “exact” transcription of
   a document have changed over time, focusing on the oft-reprinted
   work of Chaucer.
** [[https://www.youtube.com/playlist?list=PL697F2F9434362161]["ScriptaLab Talks,"]] University of Colorado Boulder, Director, 2010-14.
   ScriptaLab aimed to find the intersection of traditional
   book-oriented bibliographical studies and media studies; it
   included a lecture series, advanced faculty seminar, and
   publication series. The videos remain on YouTube, perhaps forever?
** [[http://rbms.info/conferences2/preconferences/2013/index.html]["The 54th Annual Preconference of the Rare Books and Manuscripts Section,"]] Minneapolis, Conference Chair, 2013.
   Focused on issues in managing performance arts collections as well
   as how the work of libraries is intrinsically a performance; also
   explored LGBT issues and gender in archives and special
   collections.

* Literate Computation
** [[https://github.com/cacology/private-diary]["private-diary,"]] MELPA package for Emacs, updated 2015.
   A simple proof-of-concept using strong encryption to create a
   private diary where you can keep your gossipy gossip and salacious
   life in the world's best editor.
** [[https://github.com/cacology/cacology.github.io]["Annotated checklist of Things by or About,"]] GitHub page, update 2016.
   You're looking at it, but it’s base on an org-mode file compiled
   with pandoc and styled with bare CSS. All hand-coded, all the
   time.

* Public Ethics
** Ascher, James P. "How To Not be Creepy," /nomorepotlucks/ 27: crush (2013) [[http://nomorepotlucks.org/site/how-to-not-be-creepy-james-p-ascher/]].
   Thoughts about how the 18th century teaches us that creeping is
   eternal and that it's always creepy to stare.

* Contacts
** [[https://twitter.com/jpsa]["Twitter: @jpsa"]]
** [[mailto:jpa4q@virginia.edu]["Email: jpa4q@virginia.edu"]]
